[package]
name = "filt-rs-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[features]
default = ["fuzz-targets"]
fuzz-targets = []

[dependencies]
afl = "0.18.2"
arbitrary = { version = "1", features = ["derive"] }
filt-rs = { path = "..", features = ["chrono", "regex"] }

[[bin]]
name = "parse"
path = "fuzz_targets/parse.rs"
test = false
doc = false
bench = false
required-features = ["fuzz-targets"]

[[bin]]
name = "evaluate"
path = "fuzz_targets/evaluate.rs"
test = false
doc = false
bench = false
required-features = ["fuzz-targets"]