[package]
name = "filt-rs-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
filt-rs = { path = "..", features = ["chrono", "regex"] }
libfuzzer-sys = "0.4"

[[bin]]
name = "parse"
path = "fuzz_targets/parse.rs"
test = false
doc = false
bench = false

[[bin]]
name = "evaluate"
path = "fuzz_targets/evaluate.rs"
test = false
doc = false
bench = false